### ISSUE TITLE
issues with running on mac

### ISSUE THREAD

**Issue by gilv** [infinispan/python-client#13]
What exactly pip3 wheel . suppose to do? Is it mandatory?
I want to install Infinispan and use python client to connect there.

I run pip3 wheel .  my mac and got bunch of errors, in particular related to valgrind which we don't have for mac i think.

  HEAD is now at 2fe3bd99 Merge pull request #1433 from dsacre/fix-clang-warnings
  [ 33%] No patch step for 'googletest'
  [ 44%] Performing update step for 'googletest'
  [ 55%] No configure step for 'googletest'
  [ 66%] No build step for 'googletest'
  [ 77%] No install step for 'googletest'
  [ 88%] No test step for 'googletest'
  [100%] Completed 'googletest'
  [100%] Built target googletest
  -- Found PythonInterp: /Users/gilv/.pyenv/versions/3.6.7/bin/python (found version "3.6.7")
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Found Protobuf: /usr/local/lib/libprotobuf.dylib (found version "3.11.1")
  -- Found OpenSSL: /usr/local/opt/openssl/lib/libcrypto.dylib (found version "1.1.1d")
  CMake Error at CMakeLists.txt:485 (message):
    Cannot find valgrind in your environment.  Please install valgrind or use
    NOENABLE_VALGRIND
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/pip-req-build-vk5jmm6u/build/cpp-client/src/cppclient-build/CMakeFiles/CMakeOutput.log".
  make[2]: *** [../cpp-client/src/cppclient-stamp/cppclient-configure] Error 1
  make[1]: *** [CMakeFiles/cppclient.dir/all] Error 2
  make: *** [all] Error 2
  error: command 'cmake' failed with exit status 2
  
  ----------------------------------------
  Failed building wheel for infinispan
  Running setup.py clean for infinispan
Failed to build infinispan

**Comment by tristantarrant** [comment]
`NOENABLE_VALGRIND=1 pip3 wheel .`

**Comment by gilv** [comment]
@tristantarrant getting the same error with your suggestion..

anyway, why python-client need Infinispan itself? I want client to connect to Infinspan that installed in the cluster, not build client with Infinispan, unless i missing something obvious

**Comment by tristantarrant** [comment]
The python API is a layer on top of the native C++ Infinispan client (that's what it is building).
@rigazilla Valgrind should really be optional

**Comment by gilv** [comment]
Valgrind works on Darwin 10.x, 11.x, 12.x, 13.x, 14.x, 15.x, 16.x and 17.x (Mac OS X 10.6/7/8/9/10/11 and macOS 10.12/13)... but not on the latest we have, like 10.15.x
