### ISSUE TITLE
Security and Authorization

### ISSUE THREAD

**Issue by archymozus** [infinispan/python-client#21]
Hello.
Help me please. I am trying to connect to the infinispan cache from python3.
Nowhere did I find examples of how to register authorization(Login/Secret)
And how to use a swig, I cannot understand
Are there any working examples, or tell me which way to dig

**Comment by rigazilla** [comment]
Hi @archymozus , 
authorization (SASL) is not exposed on the python side in the current version.

This client is a wrapper around the C++ library[1] and the wrapper is generated by swig[2]
Steps to extend the current python interface are:
- identify the needed function on the C++ side
- add some glue code in `src/hotrod-facade.cpp` and `include/hotrod-facade.h`. Classes defined in `hotrod-facade.h` will be exposed on the python side. You can have an idea on how they're exposed looking at the `test.py` file;
- generate the client as described in the README.

I would like to dust off the code and produce a PR to show how to expose auth, but this project is currently not actively maintained, so  sorry but I can't guaratee any deadline.

- [1] https://github.com/infinispan/cpp-client
- [2] http://www.swig.org/Doc4.0/SWIGDocumentation.html

**Comment by archymozus** [comment]
Thanks for the quick response.
I will try

**Comment by rigazilla** [comment]
@archymozus I've added #23 to show how you can do that.

**Comment by rigazilla** [comment]
SASL authentication has been implemented via #23 .
