### ISSUE TITLE
128 Messages Till Error

### ISSUE THREAD

**Issue by sudorandom** [infinispan/python-client#6]
Per connection, if you run more than 128 commands then you will be given an error similar to this: 

Traceback (most recent call last):
  File "bug_.py", line 14, in <module>
    sys.exit(main())
  File "bug_.py", line 8, in main
    remote_cache.put("Name", "Kevin")
  File "/usr/local/lib/python2.6/dist-packages/infinispan/remotecache.py", line 65, in put
    key, val, lifespan, max_idle, ret_prev)
  File "/usr/local/lib/python2.6/dist-packages/infinispan/remotecache.py", line 232, in _do_op
    return self._get_resp(ret_prev)
  File "/usr/local/lib/python2.6/dist-packages/infinispan/remotecache.py", line 268, in _get_resp
    return RECV[op](self, st, ret_prev)
KeyError: 1

After investigating, it looks like whenever to_varint(self.counter) on line 237 returns more than one character, the format of the message becomes invalid and the infinispan server returns an unexpected response code. This error is both unexpected and not handled by throwing an appropriate exception.

Code to reproduce:

```python
import sys
from infinispan.remotecache import RemoteCache

def main():
    remote_cache = RemoteCache()
    for i in range(129):
        print 'write #%s' % (i)
        remote_cache.put("Name", "Kevin")
    return
if __name__ == "__main__":
    sys.exit(main())
```

**Comment by i0seph** [comment]
infinispan.remotecache. _get_resp function is not implemented for vlong type.
that function should be changed below.

  def _get_resp(self, ret_prev):
    #header = self._read_bytes(HEADER_RES_LEN)
    #magic, msg_id, op, st, topo_mark = struct.unpack(HEADER_RES_FMT, header)
    magic = struct.unpack('>B',  self._read_bytes(1))[0]
    # msg_id is vlong!
    msg_id = from_varint(self.s)
    op,st,topo_mark = struct.unpack('>BBB',  self._read_bytes(3))
    assert (magic == MAGIC[1]), "Got magic: %d" % magic
    return RECV[op](self, st, ret_prev)

----
plz, commit!

**Comment by galderz** [comment]
@i0seph Maybe you can send a pull request with the requested changes?

**Comment by galderz** [comment]
PR integrated, thanks
